# Generated by Django 4.2.5 on 2023-11-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=10)),
                ('front_resident', models.IntegerField()),
                ('back_resident', models.IntegerField()),
                ('phone', models.CharField(max_length=30)),
            ],
        ),
    ]
