# Generated by Django 4.2.5 on 2023-11-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_exercise_exercisepart_exercisetype_patient2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient2',
            name='front_resident',
            field=models.CharField(max_length=8),
        ),
    ]
