# Generated by Django 4.2.5 on 2023-11-24 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_alter_patient2_front_resident'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient2',
            name='memo',
            field=models.TextField(default='memo'),
        ),
    ]
