# Generated by Django 4.2.5 on 2023-11-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_patient2_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient2',
            name='front_resident',
            field=models.CharField(max_length=6),
        ),
    ]
