# Generated by Django 4.2.5 on 2023-11-26 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_alter_exerciselist_count_alter_exerciselist_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisepart',
            name='type',
            field=models.CharField(default='신전', max_length=8),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='link',
            field=models.URLField(default='https://www.iipamaster.com/prod/prodView/1026'),
        ),
    ]
