# Generated by Django 4.2.5 on 2023-11-26 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_neck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='part',
        ),
        migrations.DeleteModel(
            name='ExercisePart',
        ),
    ]
