# Generated by Django 4.2.5 on 2023-11-26 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0011_remove_exercise_part_delete_exercisepart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='type',
        ),
        migrations.DeleteModel(
            name='ExerciseType',
        ),
    ]
