# Generated by Django 4.2.5 on 2023-11-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0013_ankle_elbow_hip_knee_shoulder_trunk_wrist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ankle',
            name='arom',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ankle',
            name='prom',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='elbow',
            name='arom',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='elbow',
            name='prom',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hip',
            name='arom',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hip',
            name='prom',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='knee',
            name='arom',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='knee',
            name='prom',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='neck',
            name='arom',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='neck',
            name='prom',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shoulder',
            name='arom',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shoulder',
            name='prom',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trunk',
            name='arom',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trunk',
            name='prom',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wrist',
            name='arom',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wrist',
            name='prom',
            field=models.IntegerField(default=0),
        ),
    ]
