# Generated by Django 4.2.5 on 2023-11-29 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0016_exerciselist'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciselist',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
