# Generated by Django 4.2.5 on 2023-12-03 10:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0018_rename_arom_rom_other_rom_rename_other_arom_rom_rom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rom',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 12, 3, 10, 58, 9, 180525, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='NeckTruck',
            fields=[
                ('code', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.datetime(2023, 12, 3, 10, 58, 9, 181531, tzinfo=datetime.timezone.utc))),
                ('flextion', models.IntegerField()),
                ('extension', models.IntegerField()),
                ('left_bending', models.IntegerField()),
                ('right_bending', models.IntegerField()),
                ('left_rotation', models.IntegerField()),
                ('right_rotation', models.IntegerField()),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.part')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient2')),
            ],
        ),
    ]
