# Generated by Django 4.2.5 on 2023-12-03 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0019_alter_rom_date_necktruck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='necktruck',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 12, 3, 10, 59, 35, 209304, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='rom',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 12, 3, 10, 59, 35, 208294, tzinfo=datetime.timezone.utc)),
        ),
    ]
