# Generated by Django 4.2.5 on 2023-12-03 11:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0021_alter_necktruck_date_alter_rom_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ankle',
            fields=[
                ('code', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('flexion', models.IntegerField()),
                ('extension', models.IntegerField()),
                ('inversion', models.IntegerField()),
                ('eversion', models.IntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient2')),
            ],
        ),
        migrations.CreateModel(
            name='Elbow',
            fields=[
                ('code', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('flexion', models.IntegerField()),
                ('extension', models.IntegerField()),
                ('pronation', models.IntegerField()),
                ('supination', models.IntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient2')),
            ],
        ),
        migrations.CreateModel(
            name='Knee',
            fields=[
                ('code', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('flexion', models.IntegerField()),
                ('extension', models.IntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient2')),
            ],
        ),
        migrations.CreateModel(
            name='ShoulderHip',
            fields=[
                ('code', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('flexion', models.IntegerField()),
                ('extension', models.IntegerField()),
                ('lateral_rotation', models.IntegerField()),
                ('medial_rotation', models.IntegerField()),
                ('abduction', models.IntegerField()),
                ('adduction', models.IntegerField()),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.part')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient2')),
            ],
        ),
        migrations.CreateModel(
            name='Wrist',
            fields=[
                ('code', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('flexion', models.IntegerField()),
                ('extension', models.IntegerField()),
                ('ulnar_deviation', models.IntegerField()),
                ('radial_deviation', models.IntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient2')),
            ],
        ),
        migrations.RenameField(
            model_name='necktruck',
            old_name='flextion',
            new_name='flexion',
        ),
        migrations.DeleteModel(
            name='Rom',
        ),
    ]
