# Generated by Django 4.2.5 on 2023-12-04 04:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0024_elbow2_delete_elbow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ankle2',
            fields=[
                ('code', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('flexion_L', models.IntegerField()),
                ('flexion_R', models.IntegerField()),
                ('extension_L', models.IntegerField()),
                ('extension_R', models.IntegerField()),
                ('inversion_L', models.IntegerField()),
                ('inversion_R', models.IntegerField()),
                ('eversion_L', models.IntegerField()),
                ('eversion_R', models.IntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient2')),
            ],
        ),
        migrations.CreateModel(
            name='Knee2',
            fields=[
                ('code', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('flexion_L', models.IntegerField()),
                ('flexion_R', models.IntegerField()),
                ('extension_L', models.IntegerField()),
                ('extension_R', models.IntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient2')),
            ],
        ),
        migrations.CreateModel(
            name='Wrist2',
            fields=[
                ('code', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('flexion_L', models.IntegerField()),
                ('flexion_R', models.IntegerField()),
                ('extension_L', models.IntegerField()),
                ('extension_R', models.IntegerField()),
                ('ulnar_deviation_L', models.IntegerField()),
                ('ulnar_deviation_R', models.IntegerField()),
                ('radial_deviation_L', models.IntegerField()),
                ('radial_deviation_R', models.IntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient2')),
            ],
        ),
        migrations.RemoveField(
            model_name='knee',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='wrist',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Ankle',
        ),
        migrations.DeleteModel(
            name='Knee',
        ),
        migrations.DeleteModel(
            name='Wrist',
        ),
    ]
