# Generated by Django 4.2.5 on 2023-12-04 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0025_ankle2_knee2_wrist2_remove_knee_patient_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NeckTruck',
            new_name='NeckTrunck',
        ),
    ]
