# Generated by Django 4.2.7 on 2023-12-15 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0027_ankle2_part_elbow2_part_knee2_part_wrist2_part'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagState',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('state', models.IntegerField()),
            ],
        ),
    ]
