# Generated by Django 4.2.7 on 2023-12-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0028_diagstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagstate',
            name='state',
            field=models.IntegerField(choices=[(0, '진료 대기'), (1, '진료 중')]),
        ),
    ]
