# Generated by Django 4.2.5 on 2023-12-16 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0028_alter_exerciselist_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciselist',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 12, 16, 16, 43, 25, 201668, tzinfo=datetime.timezone.utc)),
        ),
    ]
