# Generated by Django 4.2.7 on 2023-12-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0029_alter_diagstate_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiagState',
        ),
        migrations.AddField(
            model_name='patient2',
            name='state',
            field=models.IntegerField(choices=[(-1, 'default'), (0, '진료 대기'), (1, '진료 중')], default=-1),
            preserve_default=False,
        ),
    ]
