# Generated by Django 4.2.5 on 2023-12-17 01:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0031_alter_exerciselist_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciselist',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
