# Generated by Django 4.2.5 on 2023-12-17 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0032_alter_exerciselist_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient2',
            name='clinic_memo',
            field=models.TextField(default='물리치료 메모'),
        ),
        migrations.AddField(
            model_name='patient2',
            name='exercise_memo',
            field=models.TextField(default='운동처방 메모'),
        ),
        migrations.AddField(
            model_name='patient2',
            name='rom_memo',
            field=models.TextField(default='가동범위 검사 메모'),
        ),
        migrations.AlterField(
            model_name='patient2',
            name='memo',
            field=models.TextField(default='메모'),
        ),
    ]
