# Generated by Django 4.2.5 on 2023-12-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0036_alter_patient2_clinic_memo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciselist',
            name='memo',
            field=models.TextField(blank=True, default='메모', null=True),
        ),
    ]
